# Simple workflow to run tests on a self-hosted runner

name: Test Runner

on:
  push:
    branches:
      - dev
    
jobs:
  test:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v6
      - name: Test connectivity
        run: |
          echo "Runner works!"
          hostname
          ip a